# Application configuration file. See https://github.com/typesafehub/config/blob/master/HOCON.md for more details
HOSTNAME = "bh-laptop"

#topic_monitor.bootstrap_servers = "home-linux:9092"
topic_monitor.bootstrap_servers = "localhost:9092"

topic_monitor.application_id = "kafka_monitor"

topic_monitor.client_id = null

# Topic used to let other monitors know who owns a topic.  If a monitor is added
# and starts reporting for a topic the other monitor will not know if it has just
# stopped recieving offsets or another montior has taken it over.
topic_monitor.topic_owner_topic_name = "kafka_monitor_topic_owner"

# Topic used to partition offsets by topic to each of the monitors listening.
# All monitors read the offsets and then publish to this topic with the key
# being the topic name.  They then consume from this topic so the topics to be
# monitored are divided equally between monitors.
topic_monitor.offsets_topic_name = "kafka_monitor_offsets"

# Exclude reporting metrics on the monitors internal topics
topic_monitor.exclude_monitor_offsets = true

# How many data points to use when calculating rates
topic_monitor.rate_tracker_size = 10

# How long metrics for a consumer are reported after the last offset has been seen
topic_monitor.tracker_retention = 24 hours

# If a partition has not been read from for this ammount of time the monitor
# will start reporting a stale partition metric
topic_monitor.stale_partition_age = 1 minute

topic_monitor.ownership_reporting_delay = 10 seconds

#If a client doesn't return data for more than this amount of time the client is
#restarted.
topic_monitor.dead_client_restart = 1 minute

topic_monitor.client {
	#All settings here will be passed directly to the kafka client
	#ssl.protocol: "TLSv1.2"
	security.protocol: "PLAINTEXT"
}
